const ActionTypes = {
  LOAD_MOVIES: `LOAD_MOVIES`,
  LOAD_PROMO: `LOAD_PROMO`,
  SET_FILTER_CATEGORY: `SET_FILTER_CATEGORY`,
  LOAD_REVIEWS: `LOAD_REVIEWS`,
  ADD_REVIEW: `ADD_REVIEW`,
  ADD_REVIEW_ERROR: `ADD_REVIEW_ERROR`,
  SET_FAVORITE_STATUS: `SET_FAVORITE_STATUS`,
};

export default ActionTypes;
